export const translations: Record<"te" | "hi", Record<string, string>> = {
  te: {
    "Home":"హోమ్","About Us":"మా గురించి","About us":"మా గురించి","Shop":"షాప్","Our Products":"మా ఉత్పత్తులు","Our products":"మా ఉత్పత్తులు","Blogs":"బ్లాగులు","Contact Us":"సంప్రదించండి","Contact us":"సంప్రదించండి","FAQ":"తరచుగా అడిగే ప్రశ్నలు","Track Order":"ఆర్డర్ ట్రాక్ చేయండి","Privacy Policy":"గోప్యతా విధానం","Terms & Conditions":"నిబంధనలు మరియు షరతులు","Return & Refund Policy":"రిటర్న్ మరియు రీఫండ్ విధానం","Legal":"చట్టపరమైన సమాచారం",
    "Admin":"అడ్మిన్","Sign in":"సైన్ ఇన్","Sign out":"సైన్ అవుట్","My account":"నా ఖాతా","Account":"ఖాతా","Wishlist":"విష్‌లిస్ట్","Cart":"కార్ట్","Language":"భాష","My wishlist":"నా విష్‌లిస్ట్","Primary":"ప్రధాన నావిగేషన్","Mobile":"మొబైల్ నావిగేషన్",
    "Shop Now":"ఇప్పుడే కొనండి","Explore Products":"ఉత్పత్తులు చూడండి","100% Purity":"100% స్వచ్ఛత","No chemicals, no fillers — only pure camphor.":"రసాయనాలు లేదా కల్తీ లేని స్వచ్ఛమైన కర్పూరం మాత్రమే.","Clean Burn":"శుభ్రమైన మంట","Bright, steady flame that leaves no black residue.":"నల్లటి మసి వదలని ప్రకాశవంతమైన స్థిరమైన మంట.","Long Lasting":"ఎక్కువ సేపు ఉంటుంది","Consistent burning performance.":"స్థిరమైన మండే నాణ్యత.","Pan-India Delivery":"భారతదేశమంతటా డెలివరీ","Dispatched in 1-2 days, delivered across India.":"1–2 రోజుల్లో పంపించి భారతదేశమంతటా డెలివరీ చేస్తాము.","Our range":"మా శ్రేణి","Camphor for every ritual":"ప్రతి పూజకు కర్పూరం","View all products →":"అన్ని ఉత్పత్తులు చూడండి →","Rooted in tradition, refined by quality":"సంప్రదాయంలో పుట్టి, నాణ్యతతో తీర్చిదిద్దబడింది","Read our story":"మా కథ చదవండి","Also available online":"ఆన్‌లైన్‌లో కూడా లభ్యం","Find Swastik Camphor on your favourite marketplace.":"మీకు ఇష్టమైన మార్కెట్‌ప్లేస్‌లో స్వస్తిక్ కర్పూరం పొందండి.","Latest camphor guides":"తాజా కర్పూర మార్గదర్శకాలు","Read all guides":"అన్ని మార్గదర్శకాలు చదవండి",
    "Add to cart":"కార్ట్‌లో చేర్చండి","Add to Cart":"కార్ట్‌లో చేర్చండి","Buy now":"ఇప్పుడే కొనండి","Out of stock":"స్టాక్ లేదు","In stock":"స్టాక్‌లో ఉంది","View details":"వివరాలు చూడండి","View product details":"ఉత్పత్తి వివరాలు చూడండి","100% Pure":"100% స్వచ్ఛమైనది","Go to shop":"షాప్‌కు వెళ్లండి","All":"అన్నీ","Sort":"క్రమబద్ధీకరించండి","Most popular":"అత్యంత ప్రజాదరణ","Price: low to high":"ధర: తక్కువ నుంచి ఎక్కువ","Price: high to low":"ధర: ఎక్కువ నుంచి తక్కువ","No products in this category yet.":"ఈ విభాగంలో ఇంకా ఉత్పత్తులు లేవు.","Bring home the purest camphor":"అత్యంత స్వచ్ఛమైన కర్పూరాన్ని ఇంటికి తెచ్చుకోండి","Free shipping on orders above ₹499. Use code SWASTIK10 for 10% off your first order.":"₹499 పైబడిన ఆర్డర్లకు ఉచిత డెలివరీ. మొదటి ఆర్డర్‌పై 10% తగ్గింపుకు SWASTIK10 కోడ్ ఉపయోగించండి.","Pure camphor, crafted for every purpose":"ప్రతి అవసరానికి రూపొందించిన స్వచ్ఛమైన కర్పూరం","From daily aarti to aromatherapy and festive gifting — every product carries the same promise of purity.":"రోజువారీ హారతి నుంచి అరోమాథెరపీ, పండుగ బహుమతుల వరకు — ప్రతి ఉత్పత్తి అదే స్వచ్ఛత హామీని అందిస్తుంది.","Available in:":"లభ్యమయ్యే పరిమాణాలు:","Brand:":"బ్రాండ్:","Shipping:":"డెలివరీ:","Returns:":"రిటర్న్లు:","See our return & refund policy":"మా రిటర్న్ మరియు రీఫండ్ విధానం చూడండి","Related pooja products":"సంబంధిత పూజా ఉత్పత్తులు","Helpful camphor guides":"ఉపయోగకరమైన కర్పూర మార్గదర్శకాలు","Learn how to use camphor for aarti, store it correctly and choose the right grade.":"హారతికి కర్పూరాన్ని ఎలా ఉపయోగించాలో, సరిగ్గా ఎలా నిల్వ చేయాలో, సరైన రకాన్ని ఎలా ఎంచుకోవాలో తెలుసుకోండి.","Read the Swastik Camphor journal":"స్వస్తిక్ కర్పూరం వ్యాసాలు చదవండి","added to cart":"కార్ట్‌లో చేర్చబడింది","We could not update your wishlist.":"మీ విష్‌లిస్ట్‌ను నవీకరించలేకపోయాము.",
    "Your pooja essentials":"మీ పూజా అవసరాలు","Your cart is empty.":"మీ కార్ట్ ఖాళీగా ఉంది.","Your cart is empty":"మీ కార్ట్ ఖాళీగా ఉంది","Start shopping":"కొనుగోలు ప్రారంభించండి","Size:":"పరిమాణం:","Decrease quantity":"పరిమాణం తగ్గించండి","Increase quantity":"పరిమాణం పెంచండి","Remove":"తొలగించండి","Order summary":"ఆర్డర్ సారాంశం","Subtotal":"ఉప మొత్తం","Discount":"తగ్గింపు","Shipping":"డెలివరీ ఛార్జీ","Total":"మొత్తం","Free":"ఉచితం","Remove coupon":"కూపన్ తొలగించండి","Coupon code":"కూపన్ కోడ్","Apply":"వర్తింపజేయండి","Proceed to checkout":"చెకౌట్‌కు వెళ్లండి","Coupon applied":"కూపన్ వర్తింపజేయబడింది","Invalid coupon code":"చెల్లని కూపన్ కోడ్","Free shipping on orders above":"ఈ మొత్తానికి పైబడిన ఆర్డర్లకు ఉచిత డెలివరీ:",
    "Checkout":"చెకౌట్","Sign in to place your order":"ఆర్డర్ చేయడానికి సైన్ ఇన్ చేయండి","Your cart is saved. Sign in with a phone or email OTP and we'll bring you straight back here.":"మీ కార్ట్ భద్రంగా ఉంది. సైన్ ఇన్ చేసిన తర్వాత మిమ్మల్ని తిరిగి ఇక్కడికే తీసుకొస్తాము.","Sign in / Create account":"సైన్ ఇన్ / ఖాతా సృష్టించండి","Signing in links this order to your account so you can track it any time.":"సైన్ ఇన్ చేస్తే ఈ ఆర్డర్ మీ ఖాతాకు జత అవుతుంది, ఎప్పుడైనా ట్రాక్ చేయవచ్చు.","Order placed":"ఆర్డర్ చేయబడింది","Complete your UPI payment":"మీ UPI చెల్లింపును పూర్తి చేయండి","Your order reference is":"మీ ఆర్డర్ రిఫరెన్స్","Scan the QR below to pay. Your order is confirmed only after the payment is verified.":"చెల్లించడానికి కింది QR‌ను స్కాన్ చేయండి. చెల్లింపు ధృవీకరించిన తర్వాతే ఆర్డర్ నిర్ధారించబడుతుంది.","Browse products":"ఉత్పత్తులు చూడండి","Delivery details":"డెలివరీ వివరాలు","We confirm every order personally before dispatch.":"పంపే ముందు ప్రతి ఆర్డర్‌ను మేము వ్యక్తిగతంగా నిర్ధారిస్తాము.","Deliver to":"డెలివరీ చిరునామా","Use a new address":"కొత్త చిరునామా ఉపయోగించండి","Email":"ఇమెయిల్","Your receipt will be sent to this address from your signed-in account.":"మీరు సైన్ ఇన్ చేసిన ఈ చిరునామాకే రసీదు పంపబడుతుంది.","Full name":"పూర్తి పేరు","Phone":"ఫోన్","Delivery address":"డెలివరీ చిరునామా","City":"నగరం","State":"రాష్ట్రం","Pincode":"పిన్‌కోడ్","Save this address to my account for next time":"తదుపరి సారి కోసం ఈ చిరునామాను నా ఖాతాలో సేవ్ చేయండి","Payment method":"చెల్లింపు విధానం","Pay now with UPI / PhonePe":"UPI / PhonePeతో ఇప్పుడే చెల్లించండి","Google Pay, PhonePe, Paytm or any UPI app — secure and verified by the gateway.":"Google Pay, PhonePe, Paytm లేదా ఏదైనా UPI యాప్ — గేట్‌వే ద్వారా సురక్షితంగా ధృవీకరించబడుతుంది.","Cash on delivery":"డెలివరీ సమయంలో నగదు","Pay in cash when your order reaches your doorstep.":"మీ ఆర్డర్ ఇంటికి చేరినప్పుడు నగదుతో చెల్లించండి.","Placing order…":"ఆర్డర్ చేస్తున్నాము…","Your order":"మీ ఆర్డర్","Please enter your full name":"దయచేసి మీ పూర్తి పేరు నమోదు చేయండి","Enter a valid email":"చెల్లుబాటు అయ్యే ఇమెయిల్ నమోదు చేయండి","Enter a valid phone number":"చెల్లుబాటు అయ్యే ఫోన్ నంబర్ నమోదు చేయండి","Enter your full address":"మీ పూర్తి చిరునామా నమోదు చేయండి","Enter your city":"మీ నగరం నమోదు చేయండి","Enter your state":"మీ రాష్ట్రం నమోదు చేయండి","Enter a valid 6-digit pincode":"చెల్లుబాటు అయ్యే 6 అంకెల పిన్‌కోడ్ నమోదు చేయండి","We could not place your order. Please try again or call us.":"మీ ఆర్డర్ చేయలేకపోయాము. మళ్లీ ప్రయత్నించండి లేదా మాకు కాల్ చేయండి.",
    "Payment verified":"చెల్లింపు ధృవీకరించబడింది","Payment not completed":"చెల్లింపు పూర్తి కాలేదు","Reference received — verification in progress":"రిఫరెన్స్ అందింది — ధృవీకరణ జరుగుతోంది","Taking you to your order confirmation…":"మీ ఆర్డర్ నిర్ధారణకు తీసుకెళ్తున్నాము…","No money was captured. Scan the QR again to retry.":"డబ్బు తీసుకోబడలేదు. మళ్లీ ప్రయత్నించడానికి QR‌ను స్కాన్ చేయండి.","Our team confirms UPI transfers within a few hours. You will get an email the moment it is verified.":"మా బృందం కొన్ని గంటల్లో UPI బదిలీలను నిర్ధారిస్తుంది. ధృవీకరించిన వెంటనే మీకు ఇమెయిల్ వస్తుంది.","UPI GATEWAY":"UPI గేట్‌వే","Safe & secure transactions":"సురక్షిత లావాదేవీలు","Continue UPI payment through PhonePe Gateway.":"PhonePe గేట్‌వే ద్వారా UPI చెల్లింపును కొనసాగించండి.","Pay securely using PhonePe or any supported UPI app.":"PhonePe లేదా మద్దతున్న ఏదైనా UPI యాప్‌తో సురక్షితంగా చెల్లించండి.","Continue to UPI payment":"UPI చెల్లింపుకు కొనసాగండి","Pay with PhonePe | Fast · Secure · Trusted":"PhonePeతో చెల్లించండి | వేగం · భద్రత · నమ్మకం","Powered by PhonePe UPI Gateway":"PhonePe UPI గేట్‌వే ఆధారితం","Pay directly with UPI":"UPIతో నేరుగా చెల్లించండి","Pay with any UPI app":"ఏదైనా UPI యాప్‌తో చెల్లించండి","OR":"లేదా","Live payment — real money will be debited":"ప్రత్యక్ష చెల్లింపు — నిజమైన డబ్బు డెబిట్ అవుతుంది","Scan this gateway QR to pay":"చెల్లించడానికి ఈ గేట్‌వే QR‌ను స్కాన్ చేయండి","Scan QR code to pay":"చెల్లించడానికి QR కోడ్ స్కాన్ చేయండి","Pay exactly":"ఖచ్చితంగా చెల్లించండి","Order":"ఆర్డర్","UPI ID":"UPI ID","Copied":"కాపీ అయింది","Copy UPI ID":"UPI ID కాపీ చేయండి","Already paid? Share your UPI reference":"ఇప్పటికే చెల్లించారా? మీ UPI రిఫరెన్స్ పంపండి","Copy the 12-digit UTR / transaction ID from your UPI app receipt so we can confirm your order.":"మీ ఆర్డర్‌ను నిర్ధారించడానికి UPI యాప్ రసీదులోని 12 అంకెల UTR / లావాదేవీ IDని నమోదు చేయండి.","Submitting…":"పంపుతున్నాము…","Submit reference":"రిఫరెన్స్ పంపండి","Your order is marked paid only after the payment is verified.":"చెల్లింపు ధృవీకరించిన తర్వాత మాత్రమే మీ ఆర్డర్ చెల్లించినదిగా గుర్తించబడుతుంది.","UPI ID copied":"UPI ID కాపీ అయింది","Could not copy — please note the UPI ID manually":"కాపీ చేయలేకపోయాము — దయచేసి UPI IDను రాసుకోండి","Could not start the payment. Please try again.":"చెల్లింపును ప్రారంభించలేకపోయాము. మళ్లీ ప్రయత్నించండి.",
    "Profile":"ప్రొఫైల్","Save changes":"మార్పులు సేవ్ చేయండి","Orders":"ఆర్డర్లు","Loading your orders…":"మీ ఆర్డర్లు లోడ్ అవుతున్నాయి…","You haven't placed any orders yet.":"మీరు ఇంకా ఎలాంటి ఆర్డర్ చేయలేదు.","Track this order":"ఈ ఆర్డర్‌ను ట్రాక్ చేయండి","Your profile and order history.":"మీ ప్రొఫైల్ మరియు ఆర్డర్ చరిత్ర.","Profile updated":"ప్రొఫైల్ నవీకరించబడింది","Could not update your profile":"మీ ప్రొఫైల్‌ను నవీకరించలేకపోయాము","Saved addresses":"సేవ్ చేసిన చిరునామాలు","Loading…":"లోడ్ అవుతోంది…","No saved addresses yet.":"ఇంకా సేవ్ చేసిన చిరునామాలు లేవు.","Default":"డిఫాల్ట్","Label (Home, Office)":"పేరు (ఇల్లు, కార్యాలయం)","Address line 1":"చిరునామా లైన్ 1","Address line 2 (optional)":"చిరునామా లైన్ 2 (ఐచ్ఛికం)","Saving…":"సేవ్ చేస్తున్నాము…","Save address":"చిరునామా సేవ్ చేయండి","Cancel":"రద్దు చేయండి","Add a new address":"కొత్త చిరునామా చేర్చండి","Address saved":"చిరునామా సేవ్ చేయబడింది","Could not save that address":"ఆ చిరునామాను సేవ్ చేయలేకపోయాము","Could not remove that address":"ఆ చిరునామాను తొలగించలేకపోయాము","Notifications":"నోటిఫికేషన్లు","Mark all read":"అన్నీ చదివినట్లు గుర్తించండి","No notifications yet.":"ఇంకా నోటిఫికేషన్లు లేవు.","View order":"ఆర్డర్ చూడండి",
    "Order tracking":"ఆర్డర్ ట్రాకింగ్","Track your order":"మీ ఆర్డర్‌ను ట్రాక్ చేయండి","Enter your order ID and the email you used at checkout to see exactly where your parcel is.":"మీ పార్సెల్ ఎక్కడ ఉందో చూడటానికి ఆర్డర్ ID మరియు చెకౌట్‌లో ఉపయోగించిన ఇమెయిల్‌ను నమోదు చేయండి.","Order ID":"ఆర్డర్ ID","Email used on the order":"ఆర్డర్‌లో ఉపయోగించిన ఇమెయిల్","Looking…":"వెతుకుతున్నాము…","Track":"ట్రాక్ చేయండి","We could not find an order with those details.":"ఆ వివరాలతో ఆర్డర్ కనుగొనలేకపోయాము.","Order Placed":"ఆర్డర్ చేయబడింది","Order Confirmed":"ఆర్డర్ నిర్ధారించబడింది","Processing":"ప్రాసెస్ చేస్తున్నాము","Packed":"ప్యాక్ చేయబడింది","Shipped":"పంపబడింది","Out for Delivery":"డెలివరీకి బయలుదేరింది","Delivered":"డెలివరీ అయింది","Cancelled":"రద్దు చేయబడింది","Returned":"తిరిగి వచ్చింది","Refund Initiated":"రీఫండ్ ప్రారంభించబడింది","Refunded":"రీఫండ్ అయింది","On Hold":"నిలిపివేయబడింది","Payment Failed":"చెల్లింపు విఫలమైంది","Placed":"చేసిన తేదీ","What you ordered":"మీరు ఆర్డర్ చేసినవి","Shipment":"రవాణా","Courier":"కొరియర్","Tracking / AWB":"ట్రాకింగ్ / AWB","Expected delivery":"అంచనా డెలివరీ","Payment":"చెల్లింపు","Assigned at dispatch":"పంపేటప్పుడు కేటాయించబడుతుంది","Available once shipped":"పంపిన తర్వాత లభిస్తుంది","To be confirmed":"నిర్ధారించాల్సి ఉంది","Updates":"నవీకరణలు",
    "Payment successful 🎉":"చెల్లింపు విజయవంతమైంది 🎉","Order confirmed":"ఆర్డర్ నిర్ధారించబడింది","Payment under verification":"చెల్లింపు ధృవీకరణలో ఉంది","Verifying your payment…":"మీ చెల్లింపును ధృవీకరిస్తున్నాము…","Loading your order…":"మీ ఆర్డర్ లోడ్ అవుతోంది…","We could not load this order.":"ఈ ఆర్డర్‌ను లోడ్ చేయలేకపోయాము.","Thank you for your order 🙏":"మీ ఆర్డర్‌కు ధన్యవాదాలు 🙏","Your payment is complete and your receipt has been emailed to you. We are packing your camphor with care and will dispatch it shortly.":"మీ చెల్లింపు పూర్తయింది, రసీదు ఇమెయిల్ చేయబడింది. మీ కర్పూరాన్ని జాగ్రత్తగా ప్యాక్ చేసి త్వరలో పంపిస్తాము.","Your order is confirmed. Please keep the exact amount ready — we are packing your camphor with care and will dispatch it shortly.":"మీ ఆర్డర్ నిర్ధారించబడింది. దయచేసి ఖచ్చితమైన నగదు సిద్ధంగా ఉంచండి — మీ కర్పూరాన్ని జాగ్రత్తగా ప్యాక్ చేసి త్వరలో పంపిస్తాము.","We truly appreciate you choosing Swastik Camphor for your pooja.":"మీ పూజ కోసం స్వస్తిక్ కర్పూరాన్ని ఎంచుకున్నందుకు హృదయపూర్వక ధన్యవాదాలు.","Amount paid":"చెల్లించిన మొత్తం","Amount due":"చెల్లించాల్సిన మొత్తం","Payment status":"చెల్లింపు స్థితి","Payment reference:":"చెల్లింపు రిఫరెన్స్:","Your items":"మీ వస్తువులు","Tax":"పన్ను","View order details":"ఆర్డర్ వివరాలు చూడండి","Download receipt (PDF)":"రసీదు డౌన్‌లోడ్ చేయండి (PDF)","Continue shopping":"కొనుగోలు కొనసాగించండి","Go to my orders":"నా ఆర్డర్లకు వెళ్లండి","Payment verification in progress":"చెల్లింపు ధృవీకరణ జరుగుతోంది","Thank you — we received your payment reference":"ధన్యవాదాలు — మీ చెల్లింపు రిఫరెన్స్ అందింది","Back to my orders":"నా ఆర్డర్లకు తిరిగి వెళ్లండి","Download invoice (PDF)":"ఇన్వాయిస్ డౌన్‌లోడ్ చేయండి (PDF)","Where your parcel is right now.":"మీ పార్సెల్ ప్రస్తుతం ఎక్కడ ఉందో చూడండి.","Saved for later":"తర్వాత కోసం సేవ్ చేసినవి","Your favourite camphor picks, in one place.":"మీకు ఇష్టమైన కర్పూర ఉత్పత్తులు ఒకేచోట.","Loading your wishlist…":"మీ విష్‌లిస్ట్ లోడ్ అవుతోంది…","You have not saved any products yet.":"మీరు ఇంకా ఏ ఉత్పత్తులను సేవ్ చేయలేదు.","Browse the shop":"షాప్ చూడండి",
    "Login / Sign Up":"లాగిన్ / సైన్ అప్","Please login to continue — your cart is safe and waiting.":"కొనసాగడానికి లాగిన్ చేయండి — మీ కార్ట్ భద్రంగా ఉంది.","Welcome to Swastik Camphor. Sign in securely with your Google account.":"స్వస్తిక్ కర్పూరానికి స్వాగతం. మీ Google ఖాతాతో సురక్షితంగా సైన్ ఇన్ చేయండి.","Opening Google…":"Google తెరుస్తున్నాము…","Continue with Google":"Googleతో కొనసాగండి","Your account is created automatically the first time you sign in. We never post anything on your behalf.":"మీరు మొదటిసారి సైన్ ఇన్ చేసినప్పుడు ఖాతా స్వయంచాలకంగా సృష్టించబడుతుంది. మీ తరఫున మేము ఏదీ పోస్ట్ చేయము.","Back to home":"హోమ్‌కు తిరిగి వెళ్లండి","Google sign-in failed. Please try again.":"Google సైన్ ఇన్ విఫలమైంది. మళ్లీ ప్రయత్నించండి.","Signed in.":"సైన్ ఇన్ అయ్యారు.",
    "Customer reviews":"కస్టమర్ సమీక్షలు","Be the first to review":"మొదటి సమీక్షను ఇవ్వండి","Write a review":"సమీక్ష రాయండి","Your name":"మీ పేరు","Rating":"రేటింగ్","How was":"ఎలా ఉంది","Submit review":"సమీక్ష పంపండి","Thank you! Your review will appear once approved.":"ధన్యవాదాలు! ఆమోదించిన తర్వాత మీ సమీక్ష కనిపిస్తుంది.","Previous image":"మునుపటి చిత్రం","Next image":"తదుపరి చిత్రం",
    "We would love to hear from you":"మీ మాట వినడానికి మేము సిద్ధంగా ఉన్నాము","Questions about our camphor, a bulk order for your temple, or feedback — our Hyderabad team is happy to help.":"మా కర్పూరం, ఆలయానికి పెద్ద ఆర్డర్ లేదా అభిప్రాయం గురించి ప్రశ్నలుంటే — మా హైదరాబాద్ బృందం సహాయం చేస్తుంది.","Send us a message":"మాకు సందేశం పంపండి","Email address":"ఇమెయిల్ చిరునామా","Phone (optional)":"ఫోన్ (ఐచ్ఛికం)","Subject":"విషయం","Message":"సందేశం","Sending…":"పంపుతున్నాము…","Send message":"సందేశం పంపండి","Thank you for reaching out — we usually reply within one business day.":"సంప్రదించినందుకు ధన్యవాదాలు — సాధారణంగా ఒక పని దినంలో సమాధానం ఇస్తాము.","Reach us directly":"నేరుగా సంప్రదించండి","Monday – Saturday, 9:30 AM – 7:00 PM IST":"సోమవారం – శనివారం, ఉదయం 9:30 – సాయంత్రం 7:00 IST","Chat on WhatsApp":"WhatsAppలో చాట్ చేయండి","Visit our location":"మా ప్రదేశాన్ని సందర్శించండి","Loading map…":"మ్యాప్ లోడ్ అవుతోంది…","Get Directions":"దారి చూడండి","Chat with us on WhatsApp":"WhatsAppలో మాతో చాట్ చేయండి",
    "Frequently asked questions":"తరచుగా అడిగే ప్రశ్నలు","Everything you may want to know before you light your next camphor flame.":"మీ తదుపరి కర్పూర జ్యోతిని వెలిగించే ముందు తెలుసుకోవాలనుకునే విషయాలన్నీ.","Is Swastik Camphor 100% pure?":"స్వస్తిక్ కర్పూరం 100% స్వచ్ఛమైనదా?","Yes. All our camphor is 100% pure and natural, free from harmful chemicals and adulterants, and quality checked batch by batch.":"అవును. మా కర్పూరం 100% స్వచ్ఛమైనది, సహజమైనది, హానికర రసాయనాలు మరియు కల్తీ లేనిది. ప్రతి బ్యాచ్ నాణ్యతను పరీక్షిస్తాము.","What is the difference between camphor tablets and Bhimseni camphor?":"కర్పూరం బిళ్లలు మరియు భీమసేని కర్పూరం మధ్య తేడా ఏమిటి?","Camphor tablets are ideal for daily pooja and aarti with a clean, residue-free burn. Bhimseni camphor is natural crystal camphor prized for rituals, Ayurvedic use and aromatherapy.":"కర్పూరం బిళ్లలు రోజువారీ పూజ, హారతికి అనుకూలం. భీమసేని కర్పూరం పూజలు, ఆయుర్వేద ఉపయోగం మరియు అరోమాథెరపీకి ప్రసిద్ధమైన సహజ స్ఫటిక కర్పూరం.","Do you deliver across India?":"భారతదేశమంతటా డెలివరీ చేస్తారా?","Yes. We ship pan-India. Orders are usually dispatched within 1-2 business days and delivered in 3-7 business days depending on your location.":"అవును. భారతదేశమంతటా పంపిస్తాము. సాధారణంగా 1–2 పని దినాల్లో పంపించి, మీ ప్రాంతాన్ని బట్టి 3–7 పని దినాల్లో డెలివరీ చేస్తాము.","Is shipping free?":"డెలివరీ ఉచితమా?","Shipping is free on orders above ₹499. Below that, a flat ₹49 shipping charge applies.":"₹499 పైబడిన ఆర్డర్లకు డెలివరీ ఉచితం. అంతకంటే తక్కువైతే ₹49 ఛార్జీ వర్తిస్తుంది.","Can I place a bulk or wholesale order?":"పెద్ద లేదా హోల్‌సేల్ ఆర్డర్ చేయవచ్చా?","How should camphor be stored?":"కర్పూరాన్ని ఎలా నిల్వ చేయాలి?","Keep camphor in an airtight container, away from direct sunlight and heat, so it retains its fragrance and does not evaporate.":"కర్పూరం సువాసన నిలిచి ఆవిరి కాకుండా గాలి చొరబడని డబ్బాలో, ఎండ మరియు వేడికి దూరంగా ఉంచండి.","Can I return a product?":"ఉత్పత్తిని తిరిగి ఇవ్వవచ్చా?","Unopened products can be returned within 7 days of delivery. Damaged or incorrect items are replaced free of charge.":"తెరవని ఉత్పత్తులను డెలివరీ అయిన 7 రోజుల్లో తిరిగి ఇవ్వవచ్చు. దెబ్బతిన్న లేదా తప్పుగా వచ్చిన వస్తువులను ఉచితంగా మార్చుతాము.","Is camphor safe to use at home?":"కర్పూరాన్ని ఇంట్లో ఉపయోగించడం సురక్షితమా?",
    "Devotion, distilled into pure camphor":"భక్తి నుంచి పుట్టిన స్వచ్ఛమైన కర్పూరం","What we stand for":"మా విలువలు","Purity":"స్వచ్ఛత","Tradition":"సంప్రదాయం","Quality":"నాణ్యత","Sustainability":"స్థిరత్వం","Only 100% pure camphor — never diluted, never chemically loaded.":"100% స్వచ్ఛమైన కర్పూరం మాత్రమే — పలుచన చేయలేదు, రసాయనాలు కలపలేదు.","Made with respect for age-old Indian rituals and pooja practices.":"పురాతన భారతీయ ఆచారాలు, పూజా పద్ధతులకు గౌరవంతో తయారు చేయబడింది.","Every batch is checked for fragrance, burn and residue-free performance.":"ప్రతి బ్యాచ్ సువాసన, మండే నాణ్యత మరియు మసి లేని పనితీరుకు పరీక్షించబడుతుంది.","Ethically sourced raw material and eco-friendly packaging.":"నైతికంగా సేకరించిన ముడి పదార్థాలు మరియు పర్యావరణ హిత ప్యాకేజింగ్.",
    "Page not found":"పేజీ కనబడలేదు","The page you're looking for doesn't exist or has been moved.":"మీరు వెతుకుతున్న పేజీ లేదు లేదా మార్చబడింది.","Go home":"హోమ్‌కు వెళ్లండి","This page didn't load":"ఈ పేజీ లోడ్ కాలేదు","Something went wrong on our end. You can try refreshing or head back home.":"మా వైపు సమస్య ఏర్పడింది. పేజీని రిఫ్రెష్ చేయండి లేదా హోమ్‌కు వెళ్లండి.","Try again":"మళ్లీ ప్రయత్నించండి","Swastik Assistant":"స్వస్తిక్ సహాయకుడు","Online • replies instantly":"ఆన్‌లైన్ • వెంటనే సమాధానం","Starting your chat…":"మీ చాట్ ప్రారంభమవుతోంది…","Your conversations":"మీ సంభాషణలు","Pick up where you left off, or start a new chat.":"ఆపిన చోట నుంచి కొనసాగించండి లేదా కొత్త చాట్ ప్రారంభించండి.","No conversations yet.":"ఇంకా సంభాషణలు లేవు.","All conversations":"అన్ని సంభాషణలు","Loading conversation…":"సంభాషణ లోడ్ అవుతోంది…","Ask about camphor, pooja, orders…":"కర్పూరం, పూజ, ఆర్డర్ల గురించి అడగండి…","Swastik Assistant is thinking…":"స్వస్తిక్ సహాయకుడు ఆలోచిస్తున్నాడు…","Skip Intro →":"పరిచయాన్ని దాటవేయండి →","Tradition in Every Moment":"ప్రతి క్షణంలో సంప్రదాయం","Purity • Tradition • Trust":"స్వచ్ఛత • సంప్రదాయం • నమ్మకం","Explore":"అన్వేషించండి","Quick Links":"త్వరిత లింక్‌లు","Reach Us":"మమ్మల్ని చేరుకోండి","Also available on":"ఇక్కడ కూడా లభ్యం","All rights reserved.":"సర్వ హక్కులు రక్షించబడ్డాయి.",
    "Code":"కోడ్","Code copied":"కోడ్ కాపీ అయింది","Use code":"ఈ కోడ్ ఉపయోగించండి","Copy code":"కోడ్ కాపీ చేయండి","off":"తగ్గింపు","First order":"మొదటి ఆర్డర్","Shop by category":"విభాగం వారీగా కొనండి","View products":"ఉత్పత్తులు చూడండి","Offers":"ఆఫర్లు","on your first order with code":"మొదటి ఆర్డర్‌పై — కోడ్","100% pure camphor with a clean, residue-free burn.":"మసి లేకుండా శుభ్రంగా మండే 100% స్వచ్ఛమైన కర్పూరం.","Trusted across Telangana":"తెలంగాణ అంతటా నమ్మకం","retail stores across Telangana":"తెలంగాణ అంతటా రిటైల్ దుకాణాలు","making pure camphor in Hyderabad":"హైదరాబాద్‌లో స్వచ్ఛమైన కర్పూరం తయారీ","Also on the shelves at":"ఈ దుకాణాల్లో కూడా లభ్యం","Ask a question on WhatsApp":"WhatsAppలో ప్రశ్న అడగండి"
  },
  hi: {}
};

// Hindi mirrors every Telugu key, then overrides each phrase below.
Object.assign(translations.hi, Object.fromEntries(Object.keys(translations.te).map((key) => [key, key])), {
  "Home":"होम","About Us":"हमारे बारे में","About us":"हमारे बारे में","Shop":"शॉप","Our Products":"हमारे उत्पाद","Our products":"हमारे उत्पाद","Blogs":"ब्लॉग","Contact Us":"संपर्क करें","Contact us":"संपर्क करें","FAQ":"सामान्य प्रश्न","Track Order":"ऑर्डर ट्रैक करें","Privacy Policy":"गोपनीयता नीति","Terms & Conditions":"नियम और शर्तें","Return & Refund Policy":"वापसी और रिफंड नीति","Legal":"कानूनी जानकारी",
  "Admin":"एडमिन","Sign in":"साइन इन","Sign out":"साइन आउट","My account":"मेरा खाता","Account":"खाता","Wishlist":"विशलिस्ट","Cart":"कार्ट","Language":"भाषा","My wishlist":"मेरी विशलिस्ट",
  "Shop Now":"अभी खरीदें","Explore Products":"उत्पाद देखें","100% Purity":"100% शुद्धता","No chemicals, no fillers — only pure camphor.":"कोई रसायन या मिलावट नहीं — केवल शुद्ध कपूर।","Clean Burn":"स्वच्छ ज्वाला","Bright, steady flame that leaves no black residue.":"चमकदार, स्थिर ज्वाला जो काली कालिख नहीं छोड़ती।","Long Lasting":"लंबे समय तक चलने वाला","Consistent burning performance.":"एक समान जलने की गुणवत्ता।","Pan-India Delivery":"पूरे भारत में डिलीवरी","Dispatched in 1-2 days, delivered across India.":"1–2 दिनों में भेजा जाता है और पूरे भारत में डिलीवरी होती है।","Our range":"हमारी श्रृंखला","Camphor for every ritual":"हर पूजा के लिए कपूर","View all products →":"सभी उत्पाद देखें →","Rooted in tradition, refined by quality":"परंपरा में जड़ें, गुणवत्ता से निखार","Read our story":"हमारी कहानी पढ़ें","Also available online":"ऑनलाइन भी उपलब्ध","Find Swastik Camphor on your favourite marketplace.":"अपने पसंदीदा मार्केटप्लेस पर स्वस्तिक कपूर पाएं।","Latest camphor guides":"नवीनतम कपूर मार्गदर्शिकाएँ","Read all guides":"सभी मार्गदर्शिकाएँ पढ़ें",
  "Add to cart":"कार्ट में डालें","Add to Cart":"कार्ट में डालें","Buy now":"अभी खरीदें","Out of stock":"स्टॉक में नहीं","In stock":"स्टॉक में है","View details":"विवरण देखें","View product details":"उत्पाद विवरण देखें","100% Pure":"100% शुद्ध","Go to shop":"शॉप पर जाएँ","All":"सभी","Sort":"क्रमबद्ध करें","Most popular":"सबसे लोकप्रिय","Price: low to high":"मूल्य: कम से अधिक","Price: high to low":"मूल्य: अधिक से कम","No products in this category yet.":"इस श्रेणी में अभी कोई उत्पाद नहीं है।","Bring home the purest camphor":"सबसे शुद्ध कपूर घर लाएँ","Free shipping on orders above ₹499. Use code SWASTIK10 for 10% off your first order.":"₹499 से अधिक के ऑर्डर पर मुफ़्त डिलीवरी। पहले ऑर्डर पर 10% छूट के लिए SWASTIK10 कोड लगाएँ।","Pure camphor, crafted for every purpose":"हर उपयोग के लिए तैयार शुद्ध कपूर","Available in:":"उपलब्ध आकार:","Brand:":"ब्रांड:","Shipping:":"डिलीवरी:","Returns:":"वापसी:","See our return & refund policy":"हमारी वापसी और रिफंड नीति देखें","Related pooja products":"संबंधित पूजा उत्पाद","Helpful camphor guides":"उपयोगी कपूर मार्गदर्शिकाएँ","Read the Swastik Camphor journal":"स्वस्तिक कपूर लेख पढ़ें","added to cart":"कार्ट में जोड़ा गया","We could not update your wishlist.":"हम आपकी विशलिस्ट अपडेट नहीं कर सके।",
  "Your pooja essentials":"आपकी पूजा सामग्री","Your cart is empty.":"आपका कार्ट खाली है।","Your cart is empty":"आपका कार्ट खाली है","Start shopping":"खरीदारी शुरू करें","Size:":"आकार:","Decrease quantity":"मात्रा घटाएँ","Increase quantity":"मात्रा बढ़ाएँ","Remove":"हटाएँ","Order summary":"ऑर्डर सारांश","Subtotal":"उप-योग","Discount":"छूट","Shipping":"डिलीवरी शुल्क","Total":"कुल","Free":"मुफ़्त","Remove coupon":"कूपन हटाएँ","Coupon code":"कूपन कोड","Apply":"लागू करें","Proceed to checkout":"चेकआउट करें","Coupon applied":"कूपन लागू हुआ","Invalid coupon code":"अमान्य कूपन कोड","Free shipping on orders above":"इस राशि से अधिक के ऑर्डर पर मुफ़्त डिलीवरी:",
  "Checkout":"चेकआउट","Sign in to place your order":"ऑर्डर करने के लिए साइन इन करें","Your cart is saved. Sign in with a phone or email OTP and we'll bring you straight back here.":"आपका कार्ट सुरक्षित है। साइन इन करने के बाद आप यहीं लौटेंगे।","Sign in / Create account":"साइन इन / खाता बनाएँ","Signing in links this order to your account so you can track it any time.":"साइन इन करने से यह ऑर्डर आपके खाते से जुड़ता है और आप इसे कभी भी ट्रैक कर सकते हैं।","Order placed":"ऑर्डर किया गया","Complete your UPI payment":"अपना UPI भुगतान पूरा करें","Your order reference is":"आपका ऑर्डर रेफरेंस","Scan the QR below to pay. Your order is confirmed only after the payment is verified.":"भुगतान के लिए नीचे QR स्कैन करें। भुगतान सत्यापित होने के बाद ही ऑर्डर पक्का होगा।","Browse products":"उत्पाद देखें","Delivery details":"डिलीवरी विवरण","We confirm every order personally before dispatch.":"भेजने से पहले हम हर ऑर्डर की व्यक्तिगत पुष्टि करते हैं।","Deliver to":"यहाँ डिलीवर करें","Use a new address":"नया पता उपयोग करें","Email":"ईमेल","Your receipt will be sent to this address from your signed-in account.":"रसीद आपके साइन-इन खाते के इसी पते पर भेजी जाएगी।","Full name":"पूरा नाम","Phone":"फ़ोन","Delivery address":"डिलीवरी पता","City":"शहर","State":"राज्य","Pincode":"पिनकोड","Save this address to my account for next time":"अगली बार के लिए यह पता मेरे खाते में सहेजें","Payment method":"भुगतान विधि","Pay now with UPI / PhonePe":"UPI / PhonePe से अभी भुगतान करें","Google Pay, PhonePe, Paytm or any UPI app — secure and verified by the gateway.":"Google Pay, PhonePe, Paytm या कोई UPI ऐप — गेटवे द्वारा सुरक्षित और सत्यापित।","Cash on delivery":"कैश ऑन डिलीवरी","Pay in cash when your order reaches your doorstep.":"ऑर्डर घर पहुँचने पर नकद भुगतान करें।","Placing order…":"ऑर्डर किया जा रहा है…","Your order":"आपका ऑर्डर","Please enter your full name":"कृपया अपना पूरा नाम दर्ज करें","Enter a valid email":"मान्य ईमेल दर्ज करें","Enter a valid phone number":"मान्य फ़ोन नंबर दर्ज करें","Enter your full address":"अपना पूरा पता दर्ज करें","Enter your city":"अपना शहर दर्ज करें","Enter your state":"अपना राज्य दर्ज करें","Enter a valid 6-digit pincode":"मान्य 6 अंकों का पिनकोड दर्ज करें","We could not place your order. Please try again or call us.":"हम आपका ऑर्डर नहीं कर सके। फिर प्रयास करें या हमें कॉल करें।",
  "Payment verified":"भुगतान सत्यापित","Payment not completed":"भुगतान पूरा नहीं हुआ","Reference received — verification in progress":"रेफरेंस मिला — सत्यापन जारी है","Taking you to your order confirmation…":"आपको ऑर्डर पुष्टि पर ले जाया जा रहा है…","No money was captured. Scan the QR again to retry.":"कोई राशि नहीं कटी। दोबारा प्रयास के लिए QR स्कैन करें।","UPI GATEWAY":"UPI गेटवे","Safe & secure transactions":"सुरक्षित लेनदेन","Continue UPI payment through PhonePe Gateway.":"PhonePe गेटवे से UPI भुगतान जारी रखें।","Pay securely using PhonePe or any supported UPI app.":"PhonePe या समर्थित UPI ऐप से सुरक्षित भुगतान करें।","Continue to UPI payment":"UPI भुगतान जारी रखें","Powered by PhonePe UPI Gateway":"PhonePe UPI गेटवे द्वारा संचालित","Pay directly with UPI":"UPI से सीधे भुगतान करें","Pay with any UPI app":"किसी भी UPI ऐप से भुगतान करें","OR":"या","Live payment — real money will be debited":"लाइव भुगतान — वास्तविक राशि कटेगी","Scan this gateway QR to pay":"भुगतान के लिए यह गेटवे QR स्कैन करें","Scan QR code to pay":"भुगतान के लिए QR स्कैन करें","Pay exactly":"ठीक इतनी राशि दें","Order":"ऑर्डर","Copied":"कॉपी हुआ","Copy UPI ID":"UPI ID कॉपी करें","Already paid? Share your UPI reference":"भुगतान कर चुके हैं? UPI रेफरेंस दें","Submitting…":"भेजा जा रहा है…","Submit reference":"रेफरेंस भेजें","Your order is marked paid only after the payment is verified.":"भुगतान सत्यापित होने के बाद ही ऑर्डर को भुगतान हुआ माना जाएगा।","UPI ID copied":"UPI ID कॉपी हुआ","Could not start the payment. Please try again.":"भुगतान शुरू नहीं हो सका। फिर प्रयास करें।",
  "Profile":"प्रोफ़ाइल","Save changes":"बदलाव सहेजें","Orders":"ऑर्डर","Loading your orders…":"आपके ऑर्डर लोड हो रहे हैं…","You haven't placed any orders yet.":"आपने अभी तक कोई ऑर्डर नहीं किया है।","Track this order":"यह ऑर्डर ट्रैक करें","Your profile and order history.":"आपकी प्रोफ़ाइल और ऑर्डर इतिहास।","Profile updated":"प्रोफ़ाइल अपडेट हुई","Could not update your profile":"प्रोफ़ाइल अपडेट नहीं हो सकी","Saved addresses":"सहेजे गए पते","Loading…":"लोड हो रहा है…","No saved addresses yet.":"अभी कोई सहेजा हुआ पता नहीं है।","Default":"डिफ़ॉल्ट","Label (Home, Office)":"नाम (घर, कार्यालय)","Address line 1":"पता पंक्ति 1","Address line 2 (optional)":"पता पंक्ति 2 (वैकल्पिक)","Saving…":"सहेजा जा रहा है…","Save address":"पता सहेजें","Cancel":"रद्द करें","Add a new address":"नया पता जोड़ें","Address saved":"पता सहेजा गया","Could not save that address":"वह पता सहेजा नहीं जा सका","Could not remove that address":"वह पता हटाया नहीं जा सका","Notifications":"सूचनाएँ","Mark all read":"सभी को पढ़ा हुआ मानें","No notifications yet.":"अभी कोई सूचना नहीं है।","View order":"ऑर्डर देखें",
  "Order tracking":"ऑर्डर ट्रैकिंग","Track your order":"अपना ऑर्डर ट्रैक करें","Enter your order ID and the email you used at checkout to see exactly where your parcel is.":"पार्सल कहाँ है यह देखने के लिए ऑर्डर ID और चेकआउट में उपयोग किया ईमेल दर्ज करें।","Order ID":"ऑर्डर ID","Email used on the order":"ऑर्डर में उपयोग किया ईमेल","Looking…":"खोज रहे हैं…","Track":"ट्रैक करें","We could not find an order with those details.":"इन विवरणों से कोई ऑर्डर नहीं मिला।","Order Placed":"ऑर्डर किया गया","Order Confirmed":"ऑर्डर पक्का हुआ","Processing":"तैयार हो रहा है","Packed":"पैक किया गया","Shipped":"भेज दिया गया","Out for Delivery":"डिलीवरी के लिए निकला","Delivered":"डिलीवर हुआ","Cancelled":"रद्द हुआ","Returned":"वापस आया","Refund Initiated":"रिफंड शुरू हुआ","Refunded":"रिफंड हुआ","On Hold":"रोक पर","Payment Failed":"भुगतान विफल","Placed":"ऑर्डर की तारीख","What you ordered":"आपके ऑर्डर की चीज़ें","Shipment":"शिपमेंट","Courier":"कूरियर","Tracking / AWB":"ट्रैकिंग / AWB","Expected delivery":"अनुमानित डिलीवरी","Payment":"भुगतान","Assigned at dispatch":"भेजते समय तय होगा","Available once shipped":"भेजने के बाद उपलब्ध","To be confirmed":"पुष्टि बाकी","Updates":"अपडेट",
  "Payment successful 🎉":"भुगतान सफल 🎉","Order confirmed":"ऑर्डर पक्का हुआ","Payment under verification":"भुगतान सत्यापन में है","Verifying your payment…":"भुगतान सत्यापित हो रहा है…","Loading your order…":"आपका ऑर्डर लोड हो रहा है…","We could not load this order.":"यह ऑर्डर लोड नहीं हो सका।","Thank you for your order 🙏":"आपके ऑर्डर के लिए धन्यवाद 🙏","Your payment is complete and your receipt has been emailed to you. We are packing your camphor with care and will dispatch it shortly.":"आपका भुगतान पूरा हो गया और रसीद ईमेल कर दी गई है। हम कपूर को सावधानी से पैक करके जल्द भेजेंगे।","Your order is confirmed. Please keep the exact amount ready — we are packing your camphor with care and will dispatch it shortly.":"आपका ऑर्डर पक्का है। कृपया सही नकद राशि तैयार रखें — हम कपूर को सावधानी से पैक करके जल्द भेजेंगे।","We truly appreciate you choosing Swastik Camphor for your pooja.":"अपनी पूजा के लिए स्वस्तिक कपूर चुनने पर आपका हार्दिक धन्यवाद।","Amount paid":"भुगतान राशि","Amount due":"देय राशि","Payment status":"भुगतान स्थिति","Payment reference:":"भुगतान रेफरेंस:","Your items":"आपकी वस्तुएँ","Tax":"कर","View order details":"ऑर्डर विवरण देखें","Download receipt (PDF)":"रसीद डाउनलोड करें (PDF)","Continue shopping":"खरीदारी जारी रखें","Go to my orders":"मेरे ऑर्डर पर जाएँ","Payment verification in progress":"भुगतान सत्यापन जारी है","Thank you — we received your payment reference":"धन्यवाद — आपका भुगतान रेफरेंस मिला","Back to my orders":"मेरे ऑर्डर पर वापस जाएँ","Download invoice (PDF)":"इनवॉइस डाउनलोड करें (PDF)","Where your parcel is right now.":"आपका पार्सल अभी कहाँ है।","Saved for later":"बाद के लिए सहेजा","Your favourite camphor picks, in one place.":"आपके पसंदीदा कपूर उत्पाद एक जगह।","Loading your wishlist…":"आपकी विशलिस्ट लोड हो रही है…","You have not saved any products yet.":"आपने अभी कोई उत्पाद नहीं सहेजा है।","Browse the shop":"शॉप देखें",
  "Login / Sign Up":"लॉगिन / साइन अप","Please login to continue — your cart is safe and waiting.":"जारी रखने के लिए लॉगिन करें — आपका कार्ट सुरक्षित है।","Welcome to Swastik Camphor. Sign in securely with your Google account.":"स्वस्तिक कपूर में आपका स्वागत है। अपने Google खाते से सुरक्षित साइन इन करें।","Opening Google…":"Google खुल रहा है…","Continue with Google":"Google से जारी रखें","Your account is created automatically the first time you sign in. We never post anything on your behalf.":"पहली बार साइन इन करने पर आपका खाता अपने आप बन जाता है। हम आपकी ओर से कुछ पोस्ट नहीं करते।","Back to home":"होम पर वापस जाएँ","Google sign-in failed. Please try again.":"Google साइन इन विफल रहा। फिर प्रयास करें।","Signed in.":"साइन इन हो गया।",
  "Customer reviews":"ग्राहक समीक्षाएँ","Be the first to review":"पहली समीक्षा लिखें","Write a review":"समीक्षा लिखें","Your name":"आपका नाम","Rating":"रेटिंग","How was":"कैसा था","Submit review":"समीक्षा भेजें","Thank you! Your review will appear once approved.":"धन्यवाद! स्वीकृति के बाद आपकी समीक्षा दिखाई देगी।","Previous image":"पिछली तस्वीर","Next image":"अगली तस्वीर",
  "We would love to hear from you":"हम आपसे सुनना चाहेंगे","Questions about our camphor, a bulk order for your temple, or feedback — our Hyderabad team is happy to help.":"कपूर, मंदिर के बड़े ऑर्डर या प्रतिक्रिया से जुड़े प्रश्नों में हमारी हैदराबाद टीम आपकी सहायता करेगी।","Send us a message":"हमें संदेश भेजें","Email address":"ईमेल पता","Phone (optional)":"फ़ोन (वैकल्पिक)","Subject":"विषय","Message":"संदेश","Sending…":"भेजा जा रहा है…","Send message":"संदेश भेजें","Thank you for reaching out — we usually reply within one business day.":"संपर्क करने के लिए धन्यवाद — हम सामान्यतः एक कार्यदिवस में उत्तर देते हैं।","Reach us directly":"सीधे संपर्क करें","Monday – Saturday, 9:30 AM – 7:00 PM IST":"सोमवार – शनिवार, सुबह 9:30 – शाम 7:00 IST","Chat on WhatsApp":"WhatsApp पर चैट करें","Visit our location":"हमारे स्थान पर आएँ","Loading map…":"नक्शा लोड हो रहा है…","Get Directions":"दिशा-निर्देश पाएँ","Chat with us on WhatsApp":"WhatsApp पर हमसे चैट करें",
  "Frequently asked questions":"अक्सर पूछे जाने वाले प्रश्न","Everything you may want to know before you light your next camphor flame.":"अगली कपूर ज्योति जलाने से पहले वह सब जो आप जानना चाहें।","Is Swastik Camphor 100% pure?":"क्या स्वस्तिक कपूर 100% शुद्ध है?","Yes. All our camphor is 100% pure and natural, free from harmful chemicals and adulterants, and quality checked batch by batch.":"हाँ। हमारा कपूर 100% शुद्ध और प्राकृतिक है, हानिकारक रसायनों और मिलावट से मुक्त है और हर बैच की गुणवत्ता जाँची जाती है।","What is the difference between camphor tablets and Bhimseni camphor?":"कपूर की टिकिया और भीमसेनी कपूर में क्या अंतर है?","Do you deliver across India?":"क्या आप पूरे भारत में डिलीवरी करते हैं?","Yes. We ship pan-India. Orders are usually dispatched within 1-2 business days and delivered in 3-7 business days depending on your location.":"हाँ। हम पूरे भारत में भेजते हैं। ऑर्डर सामान्यतः 1–2 कार्यदिवस में भेजे और स्थान के अनुसार 3–7 कार्यदिवस में डिलीवर होते हैं।","Is shipping free?":"क्या डिलीवरी मुफ़्त है?","Shipping is free on orders above ₹499. Below that, a flat ₹49 shipping charge applies.":"₹499 से अधिक के ऑर्डर पर डिलीवरी मुफ़्त है। इससे कम पर ₹49 शुल्क लगता है।","Can I place a bulk or wholesale order?":"क्या मैं थोक ऑर्डर कर सकता हूँ?","How should camphor be stored?":"कपूर कैसे रखना चाहिए?","Keep camphor in an airtight container, away from direct sunlight and heat, so it retains its fragrance and does not evaporate.":"कपूर को धूप और गर्मी से दूर, हवा-बंद डिब्बे में रखें ताकि खुशबू बनी रहे और वह उड़ न जाए।","Can I return a product?":"क्या मैं उत्पाद वापस कर सकता हूँ?","Unopened products can be returned within 7 days of delivery. Damaged or incorrect items are replaced free of charge.":"बिना खुले उत्पाद डिलीवरी के 7 दिनों में लौटाए जा सकते हैं। खराब या गलत वस्तु मुफ़्त बदली जाती है।","Is camphor safe to use at home?":"क्या घर में कपूर उपयोग करना सुरक्षित है?",
  "Devotion, distilled into pure camphor":"भक्ति से निर्मित शुद्ध कपूर","What we stand for":"हमारे मूल्य","Purity":"शुद्धता","Tradition":"परंपरा","Quality":"गुणवत्ता","Sustainability":"स्थिरता","Only 100% pure camphor — never diluted, never chemically loaded.":"केवल 100% शुद्ध कपूर — न पतला, न रसायनयुक्त।","Made with respect for age-old Indian rituals and pooja practices.":"प्राचीन भारतीय रीति-रिवाजों और पूजा परंपराओं के सम्मान से बनाया गया।","Every batch is checked for fragrance, burn and residue-free performance.":"हर बैच की सुगंध, जलने और अवशेष-मुक्त गुणवत्ता जाँची जाती है।","Ethically sourced raw material and eco-friendly packaging.":"नैतिक रूप से प्राप्त कच्चा माल और पर्यावरण-अनुकूल पैकेजिंग।",
  "Page not found":"पृष्ठ नहीं मिला","The page you're looking for doesn't exist or has been moved.":"जिस पृष्ठ को आप खोज रहे हैं वह मौजूद नहीं है या हटा दिया गया है।","Go home":"होम जाएँ","This page didn't load":"यह पृष्ठ लोड नहीं हुआ","Something went wrong on our end. You can try refreshing or head back home.":"हमारी ओर से समस्या हुई। पृष्ठ रीफ़्रेश करें या होम जाएँ।","Try again":"फिर प्रयास करें","Swastik Assistant":"स्वस्तिक सहायक","Online • replies instantly":"ऑनलाइन • तुरंत जवाब","Starting your chat…":"चैट शुरू हो रही है…","Your conversations":"आपकी बातचीत","Pick up where you left off, or start a new chat.":"जहाँ छोड़ा था वहीं से जारी रखें या नई चैट शुरू करें।","No conversations yet.":"अभी कोई बातचीत नहीं है।","All conversations":"सभी बातचीत","Loading conversation…":"बातचीत लोड हो रही है…","Ask about camphor, pooja, orders…":"कपूर, पूजा, ऑर्डर के बारे में पूछें…","Swastik Assistant is thinking…":"स्वस्तिक सहायक सोच रहा है…","Skip Intro →":"परिचय छोड़ें →","Tradition in Every Moment":"हर पल में परंपरा","Purity • Tradition • Trust":"शुद्धता • परंपरा • विश्वास","Explore":"देखें","Quick Links":"त्वरित लिंक","Reach Us":"हमसे संपर्क करें","Also available on":"यहाँ भी उपलब्ध","All rights reserved.":"सर्वाधिकार सुरक्षित।"
});

Object.assign(translations.te, {
  "At Swastik Camphor, we respect your privacy. This policy explains what information we collect and how we use it.": "స్వస్తిక్ కర్పూరంలో మీ గోప్యతను గౌరవిస్తాము. మేము ఏ సమాచారాన్ని సేకరిస్తామో, దాన్ని ఎలా ఉపయోగిస్తామో ఈ విధానం వివరిస్తుంది.",
  "Information we collect": "మేము సేకరించే సమాచారం",
  "Name, email, phone number and delivery address when you place an order or contact us, along with the contents of your enquiry or chat with our assistant.": "మీరు ఆర్డర్ చేసినప్పుడు లేదా మమ్మల్ని సంప్రదించినప్పుడు పేరు, ఇమెయిల్, ఫోన్ నంబర్, డెలివరీ చిరునామా మరియు మీ ప్రశ్న లేదా సహాయకుడితో చాట్ వివరాలు.",
  "How we use it": "మేము దాన్ని ఎలా ఉపయోగిస్తాము",
  "To process and deliver your orders, respond to enquiries, improve our products and services, and send order-related updates. We never sell your data to third parties.": "మీ ఆర్డర్లను ప్రాసెస్ చేసి డెలివరీ చేయడానికి, ప్రశ్నలకు సమాధానం ఇవ్వడానికి, మా ఉత్పత్తులు మరియు సేవలను మెరుగుపరచడానికి, ఆర్డర్ నవీకరణలు పంపడానికి ఉపయోగిస్తాము. మీ డేటాను మూడవ పక్షాలకు ఎప్పుడూ అమ్మము.",
  "Data security": "డేటా భద్రత","Your information is stored securely and is accessible only to authorised team members handling your order or enquiry.": "మీ సమాచారం సురక్షితంగా నిల్వ చేయబడుతుంది. మీ ఆర్డర్ లేదా ప్రశ్నను నిర్వహించే అధీకృత బృంద సభ్యులు మాత్రమే దాన్ని చూడగలరు.",
  "Your choices": "మీ ఎంపికలు","You can request access to, correction of, or deletion of your personal data by writing to": "మీ వ్యక్తిగత డేటాను చూడటానికి, సరిచేయడానికి లేదా తొలగించడానికి ఈ చిరునామాకు రాయవచ్చు:",
  "By using this website or placing an order, you agree to the following terms.": "ఈ వెబ్‌సైట్‌ను ఉపయోగించడం లేదా ఆర్డర్ చేయడం ద్వారా కింది నిబంధనలను అంగీకరిస్తారు.",
  "Products and pricing": "ఉత్పత్తులు మరియు ధరలు","Product images are indicative. Prices, offers and availability may change without prior notice.": "ఉత్పత్తి చిత్రాలు సూచన కోసం మాత్రమే. ధరలు, ఆఫర్లు మరియు లభ్యత ముందస్తు సమాచారం లేకుండా మారవచ్చు.",
  "Orders": "ఆర్డర్లు","Every order is confirmed by our team by phone or email before dispatch. We may cancel an order if details are incomplete or the product is unavailable.": "పంపే ముందు ప్రతి ఆర్డర్‌ను మా బృందం ఫోన్ లేదా ఇమెయిల్ ద్వారా నిర్ధారిస్తుంది. వివరాలు అసంపూర్ణంగా ఉంటే లేదా ఉత్పత్తి అందుబాటులో లేకపోతే ఆర్డర్‌ను రద్దు చేయవచ్చు.",
  "Safe use": "సురక్షిత వినియోగం","Intellectual property": "మేధో సంపత్తి","All content, branding and images on this website belong to Swastik Camphor and may not be reused without permission.": "ఈ వెబ్‌సైట్‌లోని కంటెంట్, బ్రాండింగ్ మరియు చిత్రాలు స్వస్తిక్ కర్పూరానికి చెందినవి. అనుమతి లేకుండా తిరిగి ఉపయోగించరాదు.",
  "Returns": "రిటర్న్లు","Unopened products in their original packaging can be returned within 7 days of delivery. Opened camphor packs cannot be returned for hygiene and safety reasons.": "తెరవని ఉత్పత్తులను అసలు ప్యాకేజింగ్‌లో డెలివరీ అయిన 7 రోజుల్లో తిరిగి ఇవ్వవచ్చు. పరిశుభ్రత మరియు భద్రత కారణాల వల్ల తెరిచిన కర్పూరం ప్యాక్‌లను తిరిగి ఇవ్వలేరు.",
  "Damaged or wrong items": "దెబ్బతిన్న లేదా తప్పుగా వచ్చిన వస్తువులు","Share photos of the parcel within 48 hours of delivery and we will replace the item free of charge.": "డెలివరీ అయిన 48 గంటల్లో పార్సెల్ చిత్రాలు పంపండి. వస్తువును ఉచితంగా మార్చుతాము.",
  "Refunds": "రీఫండ్లు","Approved refunds are processed within 5-7 business days to the original payment method. Shipping charges are non-refundable unless the error was ours.": "ఆమోదించిన రీఫండ్లు 5–7 పని దినాల్లో అసలు చెల్లింపు విధానానికి పంపబడతాయి. పొరపాటు మాది అయితే తప్ప డెలివరీ ఛార్జీలు తిరిగి ఇవ్వబడవు.",
  "How to request": "ఎలా అభ్యర్థించాలి","or call": "లేదా కాల్ చేయండి",
  "With a deep respect for tradition and an unwavering commitment to quality, we craft camphor that is safe, fragrant and completely free from harmful chemicals.": "సంప్రదాయం పట్ల గాఢమైన గౌరవం మరియు నాణ్యత పట్ల అచంచల నిబద్ధతతో సురక్షితమైన, సువాసనగల, హానికర రసాయనాలు లేని కర్పూరాన్ని తయారు చేస్తాము.",
  "Our camphor is used in daily pooja, aarti, meditation, aromatherapy and as a natural home freshener. Whether you are a household devotee, a temple, or a wholesale buyer, we deliver the same consistent purity in every pack.": "మా కర్పూరాన్ని రోజువారీ పూజ, హారతి, ధ్యానం, అరోమాథెరపీ మరియు సహజ గృహ సువాసనగా ఉపయోగిస్తారు. గృహ వినియోగదారు, ఆలయం లేదా హోల్‌సేల్ కొనుగోలుదారు అయినా ప్రతి ప్యాక్‌లో ఒకే స్వచ్ఛతను అందిస్తాము.",
  "Based in Hyderabad and shipping across India, Swastik Camphor continues to be a name families trust for their most sacred moments.": "హైదరాబాద్ కేంద్రంగా భారతదేశమంతటా పంపిణీ చేసే స్వస్తిక్ కర్పూరం పవిత్ర క్షణాలకు కుటుంబాలు నమ్మే పేరుగా కొనసాగుతోంది.",
  "Clean-burning pure camphor tablets for daily pooja and aarti.": "రోజువారీ పూజ మరియు హారతికి శుభ్రంగా మండే స్వచ్ఛమైన కర్పూరం బిళ్లలు.","Residue-free clean burn":"మసి లేని శుభ్రమైన మంట","Bright steady flame":"ప్రకాశవంతమైన స్థిరమైన మంట","Fresh purifying fragrance":"తాజా పవిత్ర సువాసన","Daily Pooja":"రోజువారీ పూజ","Temple Use":"ఆలయ వినియోగం","Home Fragrance":"గృహ సువాసన","Natural Bhimseni camphor crystals for rituals, Ayurveda and aromatherapy.":"పూజలు, ఆయుర్వేదం మరియు అరోమాథెరపీకి సహజ భీమసేని కర్పూరం స్ఫటికాలు.","100% natural camphor":"100% సహజ కర్పూరం","Ayurvedic & aromatherapy grade":"ఆయుర్వేద మరియు అరోమాథెరపీ నాణ్యత","Cooling aroma":"చల్లని సువాసన","Aromatherapy":"అరోమాథెరపీ","Meditation":"ధ్యానం","Ayurveda":"ఆయుర్వేదం","Long-lasting cones and slabs for temples, havan and pest control.":"ఆలయాలు, హోమం మరియు కీటక నియంత్రణకు ఎక్కువసేపు మండే కోన్‌లు మరియు బ్లాక్‌లు.","Extended burn time":"ఎక్కువ మండే సమయం","Great for large spaces":"పెద్ద ప్రదేశాలకు అనుకూలం","Natural insect repellent":"సహజ కీటక నిరోధకం","Household Use":"గృహ వినియోగం","Wholesale Purchase":"హోల్‌సేల్ కొనుగోలు","A premium hamper of camphor, brass lamp and dried flowers.":"కర్పూరం, ఇత్తడి దీపం మరియు ఎండిన పూలతో ప్రీమియం బహుమతి ప్యాక్.","Standard":"ప్రామాణికం","Deluxe":"డీలక్స్","Festive premium packaging":"పండుగ ప్రీమియం ప్యాకేజింగ్","Complete pooja essentials":"సంపూర్ణ పూజా సామగ్రి","Ready to gift":"బహుమతికి సిద్ధం","Gift Packs":"బహుమతి ప్యాక్‌లు"
});

Object.assign(translations.hi, {
  "At Swastik Camphor, we respect your privacy. This policy explains what information we collect and how we use it.": "स्वस्तिक कपूर में हम आपकी गोपनीयता का सम्मान करते हैं। यह नीति बताती है कि हम कौन-सी जानकारी लेते और उसका उपयोग कैसे करते हैं।","Information we collect":"हम जो जानकारी लेते हैं","How we use it":"हम इसका उपयोग कैसे करते हैं","Data security":"डेटा सुरक्षा","Your choices":"आपके विकल्प","By using this website or placing an order, you agree to the following terms.":"इस वेबसाइट का उपयोग या ऑर्डर करके आप निम्न शर्तों से सहमत होते हैं।","Products and pricing":"उत्पाद और मूल्य","Product images are indicative. Prices, offers and availability may change without prior notice.":"उत्पाद चित्र संकेतात्मक हैं। मूल्य, ऑफ़र और उपलब्धता बिना सूचना बदल सकते हैं।","Orders":"ऑर्डर","Every order is confirmed by our team by phone or email before dispatch. We may cancel an order if details are incomplete or the product is unavailable.":"भेजने से पहले हमारी टीम हर ऑर्डर की फ़ोन या ईमेल से पुष्टि करती है। अधूरी जानकारी या अनुपलब्ध उत्पाद पर ऑर्डर रद्द हो सकता है।","Safe use":"सुरक्षित उपयोग","Intellectual property":"बौद्धिक संपदा","Returns":"वापसी","Unopened products in their original packaging can be returned within 7 days of delivery. Opened camphor packs cannot be returned for hygiene and safety reasons.":"बिना खुले उत्पाद मूल पैकिंग में डिलीवरी के 7 दिनों में लौटाए जा सकते हैं। स्वच्छता और सुरक्षा कारणों से खुले कपूर पैक वापस नहीं होंगे।","Damaged or wrong items":"खराब या गलत वस्तुएँ","Share photos of the parcel within 48 hours of delivery and we will replace the item free of charge.":"डिलीवरी के 48 घंटों में पार्सल की तस्वीरें भेजें, हम वस्तु मुफ़्त बदलेंगे।","Refunds":"रिफंड","Approved refunds are processed within 5-7 business days to the original payment method. Shipping charges are non-refundable unless the error was ours.":"स्वीकृत रिफंड 5–7 कार्यदिवस में मूल भुगतान विधि पर भेजे जाते हैं। गलती हमारी न हो तो डिलीवरी शुल्क वापस नहीं होगा।","How to request":"अनुरोध कैसे करें","or call":"या कॉल करें",
  "With a deep respect for tradition and an unwavering commitment to quality, we craft camphor that is safe, fragrant and completely free from harmful chemicals.":"परंपरा के गहरे सम्मान और गुणवत्ता की दृढ़ प्रतिबद्धता से हम सुरक्षित, सुगंधित और हानिकारक रसायनों से मुक्त कपूर बनाते हैं।","Our camphor is used in daily pooja, aarti, meditation, aromatherapy and as a natural home freshener. Whether you are a household devotee, a temple, or a wholesale buyer, we deliver the same consistent purity in every pack.":"हमारा कपूर दैनिक पूजा, आरती, ध्यान, अरोमाथेरेपी और प्राकृतिक घरेलू सुगंध में उपयोग होता है। घर, मंदिर या थोक खरीदार—हर पैक में समान शुद्धता मिलती है।","Based in Hyderabad and shipping across India, Swastik Camphor continues to be a name families trust for their most sacred moments.":"हैदराबाद स्थित और पूरे भारत में डिलीवरी करने वाला स्वस्तिक कपूर परिवारों के पवित्र क्षणों का भरोसेमंद नाम है।",
  "Clean-burning pure camphor tablets for daily pooja and aarti.":"दैनिक पूजा और आरती के लिए साफ़ जलने वाली शुद्ध कपूर टिकिया।","Residue-free clean burn":"अवशेष रहित स्वच्छ ज्वाला","Bright steady flame":"चमकदार स्थिर ज्वाला","Fresh purifying fragrance":"ताज़ी पवित्र सुगंध","Daily Pooja":"दैनिक पूजा","Temple Use":"मंदिर उपयोग","Home Fragrance":"घर की सुगंध","Natural Bhimseni camphor crystals for rituals, Ayurveda and aromatherapy.":"अनुष्ठान, आयुर्वेद और अरोमाथेरेपी के लिए प्राकृतिक भीमसेनी कपूर क्रिस्टल।","100% natural camphor":"100% प्राकृतिक कपूर","Ayurvedic & aromatherapy grade":"आयुर्वेदिक और अरोमाथेरेपी गुणवत्ता","Cooling aroma":"शीतल सुगंध","Aromatherapy":"अरोमाथेरेपी","Meditation":"ध्यान","Ayurveda":"आयुर्वेद","Long-lasting cones and slabs for temples, havan and pest control.":"मंदिर, हवन और कीट नियंत्रण के लिए लंबे समय तक जलने वाले कोन और ब्लॉक।","Extended burn time":"लंबा जलने का समय","Great for large spaces":"बड़े स्थानों के लिए उपयुक्त","Natural insect repellent":"प्राकृतिक कीट प्रतिरोधक","Household Use":"घरेलू उपयोग","Wholesale Purchase":"थोक खरीद","A premium hamper of camphor, brass lamp and dried flowers.":"कपूर, पीतल के दीपक और सूखे फूलों का प्रीमियम उपहार पैक।","Standard":"मानक","Deluxe":"डीलक्स","Festive premium packaging":"त्योहारी प्रीमियम पैकिंग","Complete pooja essentials":"संपूर्ण पूजा सामग्री","Ready to gift":"उपहार के लिए तैयार","Gift Packs":"उपहार पैक",
  "Code":"कोड","Code copied":"कोड कॉपी हो गया","Use code":"यह कोड लगाएँ","Copy code":"कोड कॉपी करें","off":"छूट","First order":"पहला ऑर्डर","Shop by category":"श्रेणी के अनुसार खरीदें","View products":"उत्पाद देखें","Offers":"ऑफ़र","on your first order with code":"पहले ऑर्डर पर — कोड","100% pure camphor with a clean, residue-free burn.":"बिना कालिख के साफ़ जलने वाला 100% शुद्ध कपूर।","Trusted across Telangana":"पूरे तेलंगाना में भरोसा","retail stores across Telangana":"तेलंगाना भर में रिटेल स्टोर","making pure camphor in Hyderabad":"हैदराबाद में शुद्ध कपूर का निर्माण","Also on the shelves at":"इन स्टोर्स पर भी उपलब्ध","Ask a question on WhatsApp":"WhatsApp पर सवाल पूछें"
});

// Mobile-first header / hero / trust update (2026-09-26).
Object.assign(translations.te, {
  "PURE CAMPHOR":"స్వచ్ఛమైన కర్పూరం","PURE TRADITION":"స్వచ్ఛమైన సంప్రదాయం","PURE":"స్వచ్ఛమైనది","SINCE":"నుండి",
  "Swastik 100% pure camphor. Made in Hyderabad, trusted since 1968.":"స్వస్తిక్ 100% స్వచ్ఛమైన కర్పూరం. హైదరాబాద్‌లో తయారు, 1968 నుండి నమ్మకం.",
  "Bhimseni Camphor Jars":"భీమసేని కర్పూరం జార్లు","Camphor Tablets Jars":"కర్పూరం ట్యాబ్లెట్ జార్లు","Camphor Tablets Pouch":"కర్పూరం ట్యాబ్లెట్ పౌచ్",
  "Twin Pack Offers":"ట్విన్ ప్యాక్ ఆఫర్లు","Twin Packs: save up to":"ట్విన్ ప్యాక్‌లు: ఆదా","Free shipping above":"ఉచిత డెలివరీ",
  "Menu":"మెనూ","Close menu":"మెనూ మూసివేయండి","Call":"కాల్ చేయండి",
  "Trusted across India":"భారతదేశమంతటా నమ్మకం","retail stores across India":"భారతదేశమంతటా రిటైల్ దుకాణాలు","Pan-India":"భారతదేశమంతటా","delivery, dispatched in 1–2 days":"డెలివరీ, 1–2 రోజుల్లో పంపిణీ",
  "Buy 2 and save more":"2 కొనండి, ఎక్కువ ఆదా చేయండి","View all offers":"అన్ని ఆఫర్లు చూడండి","Best value":"అత్యుత్తమ విలువ","Save":"ఆదా","vs 2 single jars":"2 సింగిల్ జార్ల కంటే","per 100 g":"100 గ్రా. కు","OFF":"తగ్గింపు",
  "Popular packs":"ప్రసిద్ధ ప్యాక్‌లు","every Twin Pack beats two single jars.":"ప్రతి ట్విన్ ప్యాక్ రెండు సింగిల్ జార్ల కంటే మెరుగైనది."
});
Object.assign(translations.hi, {
  "PURE CAMPHOR":"शुद्ध कपूर","PURE TRADITION":"शुद्ध परंपरा","PURE":"शुद्ध","SINCE":"से",
  "Swastik 100% pure camphor. Made in Hyderabad, trusted since 1968.":"स्वस्तिक 100% शुद्ध कपूर। हैदराबाद में बना, 1968 से भरोसेमंद।",
  "Bhimseni Camphor Jars":"भीमसेनी कपूर जार","Camphor Tablets Jars":"कपूर टैबलेट जार","Camphor Tablets Pouch":"कपूर टैबलेट पाउच",
  "Twin Pack Offers":"ट्विन पैक ऑफ़र","Twin Packs: save up to":"ट्विन पैक: बचत","Free shipping above":"मुफ़्त शिपिंग",
  "Menu":"मेनू","Close menu":"मेनू बंद करें","Call":"कॉल करें",
  "Trusted across India":"पूरे भारत में भरोसा","retail stores across India":"भारत भर में रिटेल स्टोर","Pan-India":"पैन-इंडिया","delivery, dispatched in 1–2 days":"डिलीवरी, 1–2 दिनों में भेजा जाता है",
  "Buy 2 and save more":"2 खरीदें, ज़्यादा बचाएँ","View all offers":"सभी ऑफ़र देखें","Best value":"सबसे अच्छा सौदा","Save":"बचत","vs 2 single jars":"2 सिंगल जार की तुलना में","per 100 g":"प्रति 100 ग्रा","OFF":"छूट",
  "Popular packs":"लोकप्रिय पैक","every Twin Pack beats two single jars.":"हर ट्विन पैक दो सिंगल जार से सस्ता है।"
});
Object.assign(translations.te, {
  "off":"తగ్గింపు","First order":"మొదటి ఆర్డర్","Copy code":"కోడ్ కాపీ చేయండి","Code copied":"కోడ్ కాపీ అయింది","Use code":"కోడ్ ఉపయోగించండి",
  "on MRP":"MRP పై","Add":"చేర్చండి","Only":"కేవలం","left":"మిగిలాయి",
  "Previous packs":"మునుపటి ప్యాక్‌లు","Next packs":"తదుపరి ప్యాక్‌లు","Go to page":"పేజీకి వెళ్లండి","Play carousel":"కరోసెల్ ప్లే చేయండి","Pause carousel":"కరోసెల్ ఆపండి",
  "You're saving":"మీరు ఆదా చేస్తున్నారు","on this order":"ఈ ఆర్డర్‌పై","Pack savings":"ప్యాక్ ఆదా","Steal Deal":"స్టీల్ డీల్","Free shipping":"ఉచిత డెలివరీ",
  "Twin Pack":"ట్విన్ ప్యాక్","get 2 for":"2 పొందండి","Switch to Twin Pack":"ట్విన్ ప్యాక్‌కు మారండి",
  "Order Summary":"ఆర్డర్ సారాంశం","Coupon":"కూపన్","You've unlocked FREE shipping":"మీరు ఉచిత డెలివరీ పొందారు","and the":"మరియు","more for FREE shipping":"ఉచిత డెలివరీ కోసం మరింత","Steal Deal unlocks at":"స్టీల్ డీల్ అందుబాటులోకి వస్తుంది","Free shipping progress":"ఉచిత డెలివరీ పురోగతి",
  "Filter products":"ఉత్పత్తులను ఫిల్టర్ చేయండి","Recommended":"సిఫార్సు చేయబడినవి","Biggest saving":"అత్యధిక ఆదా","products":"ఉత్పత్తులు","No products here right now.":"ఇక్కడ ప్రస్తుతం ఉత్పత్తులు లేవు.","All products":"అన్ని ఉత్పత్తులు",
  "Camphor Tablets":"కర్పూరం ట్యాబ్లెట్లు","Bhimseni Camphor":"భీమసేని కర్పూరం","Refill Pouch":"రీఫిల్ పౌచ్",
  "years":"సంవత్సరాలు","of purity, made in Hyderabad":"స్వచ్ఛత, హైదరాబాద్‌లో తయారు","Also on the shelves at":"ఇక్కడ కూడా అమ్మకంలో"
});
Object.assign(translations.hi, {
  "off":"छूट","First order":"पहला ऑर्डर","Copy code":"कोड कॉपी करें","Code copied":"कोड कॉपी हो गया","Use code":"कोड इस्तेमाल करें",
  "on MRP":"MRP पर","Add":"जोड़ें","Only":"सिर्फ़","left":"बचे हैं",
  "Previous packs":"पिछले पैक","Next packs":"अगले पैक","Go to page":"पेज पर जाएँ","Play carousel":"कैरोसेल चलाएँ","Pause carousel":"कैरोसेल रोकें",
  "You're saving":"आप बचा रहे हैं","on this order":"इस ऑर्डर पर","Pack savings":"पैक बचत","Steal Deal":"स्टील डील","Free shipping":"मुफ़्त शिपिंग",
  "Twin Pack":"ट्विन पैक","get 2 for":"2 पाएँ","Switch to Twin Pack":"ट्विन पैक पर बदलें",
  "Order Summary":"ऑर्डर सारांश","Coupon":"कूपन","You've unlocked FREE shipping":"आपको मुफ़्त शिपिंग मिल गई","and the":"और","more for FREE shipping":"मुफ़्त शिपिंग के लिए और","Steal Deal unlocks at":"स्टील डील खुलता है","Free shipping progress":"मुफ़्त शिपिंग प्रगति",
  "Filter products":"प्रोडक्ट फ़िल्टर करें","Recommended":"सुझाए गए","Biggest saving":"सबसे बड़ी बचत","products":"प्रोडक्ट","No products here right now.":"यहाँ अभी कोई प्रोडक्ट नहीं है।","All products":"सभी प्रोडक्ट",
  "Camphor Tablets":"कपूर टैबलेट","Bhimseni Camphor":"भीमसेनी कपूर","Refill Pouch":"रिफिल पाउच",
  "years":"वर्ष","of purity, made in Hyderabad":"शुद्धता के, हैदराबाद में निर्मित","Also on the shelves at":"यहाँ भी उपलब्ध"
});
