import { useCallback, useEffect, useRef, useState } from "react";
import { Loader2, QrCode, ShieldCheck, RefreshCw } from "lucide-react";
import { toast } from "sonner";
import { useServerFn } from "@tanstack/react-start";
import { useNavigate } from "@tanstack/react-router";
import QRCode from "qrcode";
import { startPayment, getPaymentState } from "@/lib/payments.functions";
import { formatINR } from "@/data/products";

/**
 * UPI-only checkout. The QR is generated by PhonePe for this exact order and
 * amount; the browser never marks anything as paid — the server re-verifies
 * the transaction with PhonePe before the order becomes PAID.
 */
export function PayWithUpi({ orderNumber, amount }: { orderNumber: string; amount: number }) {
  const start = useServerFn(startPayment);
  const state = useServerFn(getPaymentState);
  const navigate = useNavigate();

  const [busy, setBusy] = useState<string | null>(null);
  const [qrImage, setQrImage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [watching, setWatching] = useState(false);
  const [status, setStatus] = useState<string | null>(null);
  const timer = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => () => { if (timer.current) clearInterval(timer.current); }, []);

  /** Polls the authoritative server state until PhonePe returns a final result. */
  const watchPayment = useCallback(() => {
    if (timer.current) clearInterval(timer.current);
    setWatching(true);
    timer.current = setInterval(async () => {
      try {
        const result = await state({ data: { orderNumber } });
        if (result.state === "PAID") {
          if (timer.current) clearInterval(timer.current);
          setWatching(false);
          toast.success("Payment received");
          navigate({ to: "/order-success/$orderNumber", params: { orderNumber } });
        } else if (result.state === "FAILED" || result.state === "CANCELLED" || result.state === "EXPIRED") {
          if (timer.current) clearInterval(timer.current);
          setWatching(false);
          setQrImage(null);
          setStatus(null);
          setError(
            result.state === "EXPIRED"
              ? "This QR expired. Generate a new one to pay."
              : "The payment did not go through. Please try again.",
          );
        } else {
          setStatus("Waiting for your payment…");
        }
      } catch {
        /* transient network hiccup — keep polling */
      }
    }, 4000);
  }, [navigate, orderNumber, state]);

  /** Requests a fresh PhonePe UPI QR for the current order. */
  const showQr = async () => {
    setBusy("qr");
    setError(null);
    try {
      const result = await start({ data: { orderNumber, app: "qr", mobile: false } });
      if (!result.ok) {
        setError(result.error);
        return;
      }
      const raw = result.qrData;
      if (!raw) {
        setError("The gateway did not return a QR for this order. Please use a UPI app below.");
        return;
      }
      const image = raw.startsWith("data:image")
        ? raw
        : /^[A-Za-z0-9+/=\s]+$/.test(raw) && !raw.startsWith("upi://")
          ? `data:image/png;base64,${raw.replace(/\s/g, "")}`
          : await QRCode.toDataURL(raw, { width: 512, margin: 1 });
      setQrImage(image);
      setStatus("Waiting for your payment…");
      watchPayment();
    } catch {
      setError("We could not generate the QR. Please try again.");
    } finally {
      setBusy(null);
    }
  };


  return (
    <div className="card-premium p-6 md:p-8">
      <h2 className="font-display text-2xl">Pay {formatINR(amount)} securely</h2>
      <div className="gold-rule mt-3 w-14" />
      <p className="mt-4 text-sm text-muted-foreground">
        QR payment only. Scan the QR generated for this order — your order is confirmed only after the payment is
        verified with the gateway.
      </p>

      <div className="mt-6 rounded-2xl border border-gold/40 bg-card p-5 text-center">
        <p className="text-sm font-medium">Scan via any UPI app</p>

        {qrImage ? (
          <>
            <img
              src={qrImage}
              alt={`UPI QR code to pay ${formatINR(amount)} for order ${orderNumber}`}
              className="mx-auto mt-4 h-60 w-60 rounded-xl bg-white p-3 shadow-sm"
            />
            <p className="mt-3 text-xs text-muted-foreground">
              Pay exactly {formatINR(amount)} • Order {orderNumber}
            </p>
            <button
              type="button"
              onClick={showQr}
              disabled={busy !== null}
              className="mt-3 inline-flex items-center gap-2 text-xs text-muted-foreground underline underline-offset-4"
            >
              <RefreshCw className="h-3.5 w-3.5" /> Generate a new QR
            </button>
          </>
        ) : (
          <>
            <div className="relative mx-auto mt-4 flex h-60 w-60 items-center justify-center rounded-xl border border-dashed border-gold/50 bg-muted/30">
              <QrCode className="h-20 w-20 text-muted-foreground/40" />
            </div>
            <button
              type="button"
              onClick={showQr}
              disabled={busy !== null}
              className="mt-4 inline-flex items-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-medium text-primary-foreground transition-transform duration-300 hover:-translate-y-0.5 disabled:opacity-60"
            >
              {busy === "qr" ? <Loader2 className="h-4 w-4 animate-spin" /> : <QrCode className="h-4 w-4" />}
              Click to view QR
            </button>
          </>
        )}

        {watching && status && (
          <p className="mt-4 flex items-center justify-center gap-2 text-xs text-muted-foreground">
            <Loader2 className="h-3.5 w-3.5 animate-spin" /> {status}
          </p>
        )}
      </div>

      {isMobile && (
      <div className="mt-6 grid gap-3 grid-cols-3">
        {APPS.map((app) => (
          <button
            key={app.id}
            type="button"
            disabled={busy !== null}
            onClick={() => payWithApp(app.id)}
            className="flex items-center justify-center gap-2 rounded-xl border border-gold/40 bg-card px-4 py-3.5 text-sm font-medium transition-transform duration-300 hover:-translate-y-0.5 disabled:opacity-60"
          >
            <span className="h-2.5 w-2.5 rounded-full" style={{ background: app.color }} />
            {busy === app.id ? <Loader2 className="h-4 w-4 animate-spin" /> : app.label}
          </button>
        ))}
      </div>
      )}

      <p className="mt-5 flex items-center gap-2 text-xs text-muted-foreground">
        <ShieldCheck className="h-4 w-4 text-gold" /> Payments are verified with the gateway before your order is
        marked paid.
      </p>

      {error && (
        <div className="mt-5 rounded-xl border border-destructive/40 bg-destructive/5 p-4 text-sm">
          <p className="font-medium">Payment could not continue</p>
          <p className="mt-1 text-muted-foreground">{error}</p>
        </div>
      )}
    </div>
  );
}
