/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ReturnRefundPolicyRouteImport } from './routes/return-refund-policy'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedWishlistRouteImport } from './routes/_authenticated/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAdminUsersRouteImport } from './routes/admin/admin-users'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminBlogsRouteImport } from './routes/admin/blogs'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminCouponsRouteImport } from './routes/admin/coupons'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminEmailsRouteImport } from './routes/admin/emails'
import { Route as AdminHomepageRouteImport } from './routes/admin/homepage'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminPostersRouteImport } from './routes/admin/posters'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminShippingRouteImport } from './routes/admin/shipping'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AuthenticatedOrderSuccessOrderNumberRouteImport } from './routes/_authenticated/order-success.$orderNumber'
import { Route as AuthenticatedOrdersOrderNumberRouteImport } from './routes/_authenticated/orders.$orderNumber'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminOrdersIdRouteImport } from './routes/admin/orders/$id'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminProductsAddRouteImport } from './routes/admin/products/add'
import { Route as AdminProductsEditIdRouteImport } from './routes/admin/products/edit/$id'
import { Route as ApiPublicPhonepeCallbackRouteImport } from './routes/api/public/phonepe/callback'
import { Route as ApiPublicProductImageSplatRouteImport } from './routes/api/public/product-image/$'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnRefundPolicyRoute = ReturnRefundPolicyRouteImport.update({
  id: '/return-refund-policy',
  path: '/return-refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWishlistRoute = AuthenticatedWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostersRoute = AdminPostersRouteImport.update({
  id: '/posters',
  path: '/posters',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminShippingRoute = AdminShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrderSuccessOrderNumberRoute =
  AuthenticatedOrderSuccessOrderNumberRouteImport.update({
    id: '/order-success/$orderNumber',
    path: '/order-success/$orderNumber',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersOrderNumberRoute =
  AuthenticatedOrdersOrderNumberRouteImport.update({
    id: '/orders/$orderNumber',
    path: '/orders/$orderNumber',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsAddRoute = AdminProductsAddRouteImport.update({
  id: '/products/add',
  path: '/products/add',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsEditIdRoute = AdminProductsEditIdRouteImport.update({
  id: '/products/edit/$id',
  path: '/products/edit/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiPublicPhonepeCallbackRoute =
  ApiPublicPhonepeCallbackRouteImport.update({
    id: '/api/public/phonepe/callback',
    path: '/api/public/phonepe/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicProductImageSplatRoute =
  ApiPublicProductImageSplatRouteImport.update({
    id: '/api/public/product-image/$',
    path: '/api/public/product-image/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/return-refund-policy': typeof ReturnRefundPolicyRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track-order': typeof TrackOrderRoute
  '/account': typeof AuthenticatedAccountRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/admin/admin-users': typeof AdminAdminUsersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/posters': typeof AdminPostersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/api/chat': typeof ApiChatRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/order-success/$orderNumber': typeof AuthenticatedOrderSuccessOrderNumberRoute
  '/orders/$orderNumber': typeof AuthenticatedOrdersOrderNumberRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/add': typeof AdminProductsAddRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/products/edit/$id': typeof AdminProductsEditIdRoute
  '/api/public/phonepe/callback': typeof ApiPublicPhonepeCallbackRoute
  '/api/public/product-image/$': typeof ApiPublicProductImageSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/return-refund-policy': typeof ReturnRefundPolicyRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track-order': typeof TrackOrderRoute
  '/account': typeof AuthenticatedAccountRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/admin/admin-users': typeof AdminAdminUsersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/posters': typeof AdminPostersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/api/chat': typeof ApiChatRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/chat': typeof ChatIndexRoute
  '/products': typeof ProductsIndexRoute
  '/order-success/$orderNumber': typeof AuthenticatedOrderSuccessOrderNumberRoute
  '/orders/$orderNumber': typeof AuthenticatedOrdersOrderNumberRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/add': typeof AdminProductsAddRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/products/edit/$id': typeof AdminProductsEditIdRoute
  '/api/public/phonepe/callback': typeof ApiPublicPhonepeCallbackRoute
  '/api/public/product-image/$': typeof ApiPublicProductImageSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/return-refund-policy': typeof ReturnRefundPolicyRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track-order': typeof TrackOrderRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/wishlist': typeof AuthenticatedWishlistRoute
  '/admin/admin-users': typeof AdminAdminUsersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/posters': typeof AdminPostersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/api/chat': typeof ApiChatRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/_authenticated/order-success/$orderNumber': typeof AuthenticatedOrderSuccessOrderNumberRoute
  '/_authenticated/orders/$orderNumber': typeof AuthenticatedOrdersOrderNumberRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/add': typeof AdminProductsAddRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/products/edit/$id': typeof AdminProductsEditIdRoute
  '/api/public/phonepe/callback': typeof ApiPublicPhonepeCallbackRoute
  '/api/public/product-image/$': typeof ApiPublicProductImageSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/privacy-policy'
    | '/return-refund-policy'
    | '/shop'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/track-order'
    | '/account'
    | '/wishlist'
    | '/admin/admin-users'
    | '/admin/analytics'
    | '/admin/blogs'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/emails'
    | '/admin/homepage'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/posters'
    | '/admin/profile'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/shipping'
    | '/api/chat'
    | '/blogs/$slug'
    | '/chat/$threadId'
    | '/products/$slug'
    | '/admin/'
    | '/blogs/'
    | '/chat/'
    | '/products/'
    | '/order-success/$orderNumber'
    | '/orders/$orderNumber'
    | '/admin/orders/$id'
    | '/admin/products/add'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/products/edit/$id'
    | '/api/public/phonepe/callback'
    | '/api/public/product-image/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/privacy-policy'
    | '/return-refund-policy'
    | '/shop'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/track-order'
    | '/account'
    | '/wishlist'
    | '/admin/admin-users'
    | '/admin/analytics'
    | '/admin/blogs'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/emails'
    | '/admin/homepage'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/posters'
    | '/admin/profile'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/shipping'
    | '/api/chat'
    | '/blogs/$slug'
    | '/chat/$threadId'
    | '/products/$slug'
    | '/admin'
    | '/blogs'
    | '/chat'
    | '/products'
    | '/order-success/$orderNumber'
    | '/orders/$orderNumber'
    | '/admin/orders/$id'
    | '/admin/products/add'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/products/edit/$id'
    | '/api/public/phonepe/callback'
    | '/api/public/product-image/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/privacy-policy'
    | '/return-refund-policy'
    | '/shop'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/track-order'
    | '/_authenticated/account'
    | '/_authenticated/wishlist'
    | '/admin/admin-users'
    | '/admin/analytics'
    | '/admin/blogs'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/emails'
    | '/admin/homepage'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/posters'
    | '/admin/profile'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/shipping'
    | '/api/chat'
    | '/blogs/$slug'
    | '/chat/$threadId'
    | '/products/$slug'
    | '/admin/'
    | '/blogs/'
    | '/chat/'
    | '/products/'
    | '/_authenticated/order-success/$orderNumber'
    | '/_authenticated/orders/$orderNumber'
    | '/admin/orders/$id'
    | '/admin/products/add'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/products/edit/$id'
    | '/api/public/phonepe/callback'
    | '/api/public/product-image/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReturnRefundPolicyRoute: typeof ReturnRefundPolicyRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TrackOrderRoute: typeof TrackOrderRoute
  ApiChatRoute: typeof ApiChatRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ApiPublicPhonepeCallbackRoute: typeof ApiPublicPhonepeCallbackRoute
  ApiPublicProductImageSplatRoute: typeof ApiPublicProductImageSplatRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return-refund-policy': {
      id: '/return-refund-policy'
      path: '/return-refund-policy'
      fullPath: '/return-refund-policy'
      preLoaderRoute: typeof ReturnRefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wishlist': {
      id: '/_authenticated/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AuthenticatedWishlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/admin-users': {
      id: '/admin/admin-users'
      path: '/admin-users'
      fullPath: '/admin/admin-users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posters': {
      id: '/admin/posters'
      path: '/posters'
      fullPath: '/admin/posters'
      preLoaderRoute: typeof AdminPostersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/shipping': {
      id: '/admin/shipping'
      path: '/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AdminShippingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/order-success/$orderNumber': {
      id: '/_authenticated/order-success/$orderNumber'
      path: '/order-success/$orderNumber'
      fullPath: '/order-success/$orderNumber'
      preLoaderRoute: typeof AuthenticatedOrderSuccessOrderNumberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/$orderNumber': {
      id: '/_authenticated/orders/$orderNumber'
      path: '/orders/$orderNumber'
      fullPath: '/orders/$orderNumber'
      preLoaderRoute: typeof AuthenticatedOrdersOrderNumberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/add': {
      id: '/admin/products/add'
      path: '/products/add'
      fullPath: '/admin/products/add'
      preLoaderRoute: typeof AdminProductsAddRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/edit/$id': {
      id: '/admin/products/edit/$id'
      path: '/products/edit/$id'
      fullPath: '/admin/products/edit/$id'
      preLoaderRoute: typeof AdminProductsEditIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/public/phonepe/callback': {
      id: '/api/public/phonepe/callback'
      path: '/api/public/phonepe/callback'
      fullPath: '/api/public/phonepe/callback'
      preLoaderRoute: typeof ApiPublicPhonepeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/product-image/$': {
      id: '/api/public/product-image/$'
      path: '/api/public/product-image/$'
      fullPath: '/api/public/product-image/$'
      preLoaderRoute: typeof ApiPublicProductImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedWishlistRoute: typeof AuthenticatedWishlistRoute
  AuthenticatedOrderSuccessOrderNumberRoute: typeof AuthenticatedOrderSuccessOrderNumberRoute
  AuthenticatedOrdersOrderNumberRoute: typeof AuthenticatedOrdersOrderNumberRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedWishlistRoute: AuthenticatedWishlistRoute,
  AuthenticatedOrderSuccessOrderNumberRoute:
    AuthenticatedOrderSuccessOrderNumberRoute,
  AuthenticatedOrdersOrderNumberRoute: AuthenticatedOrdersOrderNumberRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPostersRoute: typeof AdminPostersRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShippingRoute: typeof AdminShippingRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminProductsAddRoute: typeof AdminProductsAddRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminProductsEditIdRoute: typeof AdminProductsEditIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBlogsRoute: AdminBlogsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPostersRoute: AdminPostersRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShippingRoute: AdminShippingRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminProductsAddRoute: AdminProductsAddRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminProductsEditIdRoute: AdminProductsEditIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReturnRefundPolicyRoute: ReturnRefundPolicyRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TrackOrderRoute: TrackOrderRoute,
  ApiChatRoute: ApiChatRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  ChatThreadIdRoute: ChatThreadIdRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ApiPublicPhonepeCallbackRoute: ApiPublicPhonepeCallbackRoute,
  ApiPublicProductImageSplatRoute: ApiPublicProductImageSplatRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
